    # --- Diary App ---
    <Location /diary/>
        RequestHeader set X-Forwarded-Prefix "/diary/"
        ProxyPass http://127.0.0.1:8003/
        ProxyPassReverse http://127.0.0.1:8003/
    </Location>
